# Generated by Django 3.1.1 on 2020-09-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
