# Generated by Django 3.1.1 on 2020-09-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0002_auto_20200907_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='dimensions',
            new_name='measurements',
        ),
    ]
